package com.example.weather_app.db

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * This class represents a single weather record in our database table.
 * We use the @Entity annotation to tell Room that this class should be a table.
 */
@Entity(tableName = "weather_records")
data class WeatherEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0, // Unique ID for each record, automatically generated by the database
    val cityName: String,
    val temperature: String,
    val condition: String,
    val humidity: String,
    val windSpeed: String,
    val timestamp: Long = System.currentTimeMillis() // Saves when the record was created
)
